[package]
name = "solar"
version = "0.1.0"
authors = ["germolinal <germolinal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calendar = {path = "../calendar"}
geometry3d = {path= "../geometry3d"}